export const SUBJECTS = [
  'Mathematics',
  'Physics',
  'Computer Science',
  'Biology',
  'Chemistry',
  'History',
  'Literature',
  'Economics',
  'Psychology',
];

export const SUBJECT_UNITS: Record<string, string[]> = {
  'Computer Science': [
    'Computational Logic',
    'Communication Skills',
    'Introduction to Computer Studies and Internet',
    'Structured Programming and Algorithms',
    'Operating Systems',
    'Database Management Systems',
    'Software Design Methods and Architectures',
    'Assembly Language Programming',
    'Computer Vision',
    'Computer Support and Maintenance',
    'Data Structures',
  ],
  Mathematics: [
    'Basic Mathematics',
    'Discrete Mathematics',
    'Probability and Statistics I',
    'Real Analysis II',
    'Advanced Calculus',
    'Complex Analysis I',
    'Methods I',
    'Fluid Mechanics I',
    'Group Theory II',
    'Linear Algebra III',
    'Ordinary Differential Equations II',
    'Introduction to Mathematical Modelling',
    'Research Methods',
  ],
  Physics: [
    'CMJ 1100 - Communication Skills, 3 Credit Hours',
    'PHY 1103 - Physics Laboratory I, 3 Credit Hours',
    'PHY 1104 - Mechanics, 3 Credit Hours',
    'PHY 1105 - Introduction to Thermodynamics, 3 Credit Hours',
    'CHE 1104 - Physical chemistry I, 3 Credit Hours',
    'COM 1103 - Introduction to computers and Computing, 3 Credit Hours',
    'MAT 1104 - Differential Calculus, 3 Credit Hours',
    'ZOO 1100 - HIV & AIDS and Lifestyle diseases, 3 Credit Hours',
  ],
  Biology: [
    'Introduction to Biology',
    'Cell Biology',
    'Microbiology',
    'Genetics',
    'Molecular Biology',
    'Ecology',
    'Evolutionary Biology',
    'Plant Physiology/Taxonomy',
    'Zoology/Invertebrate & Vertebrate Studies',
  ],
  Chemistry: [
    'Introduction to Organic Chemistry',
    'Aromatic Compounds',
    'Stereochemistry',
    'Reaction Mechanisms',
    'Amino Acids/Peptides',
  ],
  History: [
    'Introduction to History',
    'Historiography',
    'Research Methods',
    'African History',
    'European History',
    'Area Studies (e.g., Central Europe)',
    'Gender Issues',
    'Philosophy of History',
    'Economic History',
    'International Relations',
  ],
  Literature: [
    'Literary Appreciation',
    'Introduction to Fiction',
    'Poetry',
    'Drama',
    'Principles of Criticism',
    'Advanced Theory',
    'Research Methods',
    'The Novel',
    'Short Stories',
    'Drama and Theatre Arts',
    'African Literature (Oral & Written)',
    'Caribbean Literature',
    "Children's Literature",
    'World Literature in English',
  ],
  Economics: [
    'Introduction to Microeconomics',
    'Introduction to Macroeconomics',
    'Mathematics for Economics I',
    'Mathematics for Economics II',
    'Basic Statistics',
    'Accounting I',
    'Communication Skills',
    'Computer Applications',
    'Intermediate Microeconomics',
    'Intermediate Macroeconomics',
    'Calculus for Economists',
    'Economic Statistics II',
    'Development Economics',
    'Environmental Economics',
    'History of Economic Thought',
    'Advanced Econometrics',
    'Production Economics',
    'Public Sector Economics',
    'Monetary Economics',
    'Financial Economics',
    'Research Project/Paper',
    'International Economics',
    'Institutional Economics',
    'Project Evaluation',
    'Health Economics',
    'Advanced Topics in Economic Policy',
  ],
  Psychology: [
    'Introduction to Psychology',
    'Biological Psychology',
    'Cognitive Psychology',
    'Developmental Psychology',
    'Social Psychology',
    'Abnormal Psychology',
    'Psychology of Personality',
    'Psychology and Crime',
    'Research Methods in Psychology',
    'Statistics/Quantitative Methods',
    'Data Analysis',
    'Counseling Techniques',
    'Health Psychology',
    'Industrial/Organizational Psychology',
    'Clinical Psychology',
    'Gerontology Counseling',
    'Environmental Psychology',
  ],
};

export const getUnitsForSubject = (subject: string) => SUBJECT_UNITS[subject] || [];
